spring:
  application:
    name: human_resource
  datasource:
    url: jdbc:h2:mem:humanResource
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop


server:
  port: 9090

logging:
  level:
    org.springframework : INFO
    fr.springframework : DEBUG

