spring:
  application:
    name: human_resource
  datasource:
    url: jdbc:postgresql://localhost:5432/human_resource
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/human_resource_keycloak
#          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

#jwt:
#  auth:
#    converter:
#      resource-id: HR-client
#      principal-attribute: principal_username

server:
  port: 9090

logging:
  level:
    org.springframework : INFO
    fr.springframework : DEBUG
    org:
      springframework:
        security: DEBUG
